### ISSUE TITLE
可以自定义f1按键吗,跟我的截图快捷键冲突了

### ISSUE THREAD

**Issue by 871890180** [syhyz1990/panAI#12]

**Comment by vic233333** [comment]
编辑页面，按`Ctrl+R`，输入要替换的内容`f1`，按`Enter`确认，然后键入你想要的按键，全部替换，按`Ctrl+S`保存，解决。
希望能帮到你。

**Comment by vic233333** [comment]
脚本编辑页面进入方法：
<img width="196" alt="Snipaste_2022-11-23_14-57-13" src="https://user-images.githubusercontent.com/93087330/203489212-a8f85945-a984-4a99-a631-f3af3063c89b.png">
<img width="1120" alt="Snipaste_2022-11-23_14-59-54" src="https://user-images.githubusercontent.com/93087330/203489222-99145642-883a-4a23-91da-1066c61b8a8b.png">

**Comment by syhyz1990** [comment]
楼上正解

**Comment by 871890180** [comment]
我之前试着不知道为啥不可以,刚才一试又好了.谢谢啦!!!
