### ISSUE TITLE
错误的识别链接

### ISSUE THREAD

**Issue by 1592363624** [syhyz1990/panAI#16]
错误的识别链接
![Shell截图_20230116130610](https://user-images.githubusercontent.com/50036597/212602703-eacd7214-f3ba-4391-948b-33f350e14b34.png)

![Shell截图_20230116130632](https://user-images.githubusercontent.com/50036597/212602735-0149a0d4-40a0-4092-add1-06c9080fbc17.png)

获取到的连接少了一部分

**Comment by ioonni** [comment]
看来不止我一个哈
