### ISSUE TITLE
需要一个自定义快捷键呼出弹窗，或者可关闭呼出弹窗功能；

### ISSUE THREAD

**Issue by Calm-er** [syhyz1990/panAI#18]
f1键位通常有其他指令需要执行，会出现键位冲突，能给个修改快捷键的功能就好了，最好呼出弹窗功能可以选择能否停用

**Comment by syhyz1990** [comment]
你可以在代码里搜索f1替换成你想要的快捷键



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月20日(周一) 上午10:00
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [syhyz1990/panAI] 需要一个自定义快捷键呼出弹窗，或者可关闭呼出弹窗功能； (Issue #18)




 
f1键位通常有其他指令需要执行，会出现键位冲突，能给个修改快捷键的功能就好了，最好呼出弹窗功能可以选择能否停用

**Comment by syhyz1990** [comment]
最新版已经可以自定义快捷键了
