### ISSUE TITLE
希望添加功能

### ISSUE THREAD

**Issue by Jeffrey131313** [syhyz1990/panAI#19]
希望能新增自动识别粘贴板中的链接 或者是打开窗口粘贴进去能识别（究极懒狗

**Comment by syhyz1990** [comment]
有这个功能，按f1就可以



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月27日(周四) 下午2:29
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [syhyz1990/panAI] 希望添加功能 (Issue #19)




 
希望能新增自动识别粘贴板中的链接 或者是打开窗口粘贴进去能识别（究极懒狗

**Comment by Jeffrey131313** [comment]
感谢
