### ISSUE TITLE
快捷键F1可以取消或者自定义吗？F1是我的截图快捷键。

### ISSUE THREAD

**Issue by 2575829997** [syhyz1990/panAI#27]
快捷键F1可以取消或者自定义吗？F1是我的截图快捷键。

**Comment by syhyz1990** [comment]
自己搜索代码中的f1，换成你想要的快捷键



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月1日(周五) 晚上11:00
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [syhyz1990/panAI] 快捷键F1可以取消或者自定义吗？F1是我的截图快捷键。 (Issue #27)




 
快捷键F1可以取消或者自定义吗？F1是我的截图快捷键。
