### ISSUE TITLE
如何跳过读取确认界面，直接打开网盘？

### ISSUE THREAD

**Issue by zbb7001** [syhyz1990/panAI#28]
- 如何修改成按下F1后就直接打开百度网盘。
- 每次都要再多点一次 `读取剪切板`  ,从未用过 `识别方框内容`，对我个人来说总觉得凭空多了一道手续。
- - 对于这个确认界面，我的认识就是有的网盘可能需要用此方法才能识别，但对于我，却从未碰到过这种情况。就觉得有点多余了。

**Comment by syhyz1990** [comment]
不授权的话js没法直接读取剪切板的，另外也无法知道是否已授权



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月12日(周四) 晚上8:00
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [syhyz1990/panAI] 如何跳过读取确认界面，直接打开网盘？ (Issue #28)




  
如何修改成按下F1后就直接打开百度网盘。
 
每次都要再多点一次 读取剪切板  ,从未用过 识别方框内容，对我个人来说总觉得凭空多了一道手续。
 
  
对于这个确认界面，我的认识就是有的网盘可能需要用此方法才能识别，但对于我，却从未碰到过这种情况。就觉得有点多余了。

**Comment by zbb7001** [comment]
明白了，感谢回复！
