### ISSUE TITLE
天翼网盘无法识别网址和密码

### ISSUE THREAD

**Issue by lyjhyjyes** [syhyz1990/panAI#3]
https://cloud.189.cn/web/share?code=R7ZR7f73aEBb
密码：n6qn
https://www.52pojie.cn/thread-1477750-1-1.html
【自写】Win10离线安装NetFrameWork工具 - 『精品软件区』 - 吾爱破解 - LCG - LSG |安卓破解|病毒分析|www.52pojie.cn

**Comment by syhyz1990** [comment]
@lyjhyjyes 更新到最新版试下
