### ISSUE TITLE
快捷键冲突

### ISSUE THREAD

**Issue by myaijarvis** [syhyz1990/panAI#30]
快捷键F1与snipate截图软件冲突，建议脚本添加一个关闭快捷键或者自定义快捷键的功能，因为脚本的快捷键功能很少会使用，希望作者能考虑一下。

**Comment by 52fisher** [comment]
这个功能已实现，已发起pr，但是作者未合并。（包括上次的更新的也没有合并，感觉作者已经很久没有上github了）
你可以 [点击这里](https://github.com/52fisher/panAI/raw/main/panai.user.js) 使用我已合并更新的版本

**Comment by syhyz1990** [comment]
@52fisher 已合并到主分支，非常感谢
