### ISSUE TITLE
国内SweetAlert2的资源地址访问不到

### ISSUE THREAD

**Issue by Bender65535** [syhyz1990/panAI#33]
国内SweetAlert2的资源地址访问不到，导致Uncaught (in promise) ReferenceError: Swal is not defined
无法正常使用插件

**Comment by 52fisher** [comment]
![图片](https://github.com/syhyz1990/panAI/assets/32198215/8382535b-80c3-4e0c-a183-ca8131f567ae)

目前应该只有西藏无法访问，特殊局域网的话还是要自己手动去替换一下的

**Comment by syhyz1990** [comment]
cdn已替换成阿里云
