### ISSUE TITLE
导致www.futbin.com这个网站所有内容无法点击？

### ISSUE THREAD

**Issue by BedObejective** [syhyz1990/panAI#35]
其他网站没啥问题，就这个居然导致页面有层遮罩一样，没法点任何链接，关了这个脚本就没事。

**Comment by 52fisher** [comment]
<s>futbin:  💩山代码出了问题  ❌
swal2 : 都怪我设置了z-index:1060 ✅
</s>


解决办法:
油猴脚本 // ==UserScript== 中  排除该网站
`// @exclude           https://www.futbin.com/*`


@syhyz1990 最新的代码合并一下
