### ISSUE TITLE
希望加入对不完整网盘链接的识别

### ISSUE THREAD

**Issue by saltyfish-xy** [syhyz1990/panAI#51]
有些人放网盘（尤其是度盘）的时候为防止链接被夹会从中间开始放（比如度盘的话就是从/s/开始放），希望能针对这种情况加入识别，谢谢

**Comment by 52fisher** [comment]
这是一个很好的想法，功能可以实现，但是可能会造成一些困扰。
需要给个具体的场景，如果没有其它任何标识符（如写明：百度网盘），没有办法推断链接的来源。比如
链接：/s/1EiCw6iRMAEzIYtZ6-JBMfA
提取码：gdo4

可能来自于 飞猫云、优云、联通云盘、UC、夸克、115、123、迅雷，如果随意推断补全，可能会造成一些不必要的错误识别。
