### ISSUE TITLE
蓝奏盘链接无法正常识别

### ISSUE THREAD

**Issue by LSQ-Code** [syhyz1990/panAI#53]
如下链接：蓝奏云 ：https://www.ilanzou.com/s/B2Reb0u

**Comment by LSQ-Code** [comment]
检查后发现此蓝奏非彼蓝奏
![QQ_1722734492924](https://github.com/user-attachments/assets/1e1c0424-bb22-430b-8acf-4ab3e0c22f86)

**Comment by 52fisher** [comment]
![QQ_1722778751256](https://github.com/user-attachments/assets/03c5bf24-0875-4021-9b22-6a2314d77c1c)
Added support for this feature.
