### ISSUE TITLE
可以使用系统提示框吗

### ISSUE THREAD

**Issue by zxk2099** [syhyz1990/panAI#6]
使用系统提示框可以在弹出的提示窗口绑定space、enter、esc键，使用键盘就可以完成确定、取消的操作，或者在现有的提示框中绑定键盘按键

**Comment by syhyz1990** [comment]
既然使用鼠标选中文本触发识别，为什么会用键盘操作？貌似说不通。

如有需要，可以fork一份自己修改成系统提示框。

**Comment by syhyz1990** [comment]
1.8.3 已经实现了按键绑定功能，Enter 确认，ESC 取消
