### ISSUE TITLE
可以更改F1快捷键吗

### ISSUE THREAD

**Issue by jasperwt** [syhyz1990/panAI#9]
可以更改F1快捷键吗

**Comment by syhyz1990** [comment]
可以，在代码里搜索F1替换成你想要的快捷键



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月21日(周二) 下午2:09
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [syhyz1990/panAI] 可以更改F1快捷键吗 (Issue #9)




 
可以更改F1快捷键吗

**Comment by jasperwt** [comment]
好滴谢谢！
